### ISSUE TITLE
WebResult HTTP Status Code

### ISSUE THREAD

**Issue by saskiaschild** [s-u/FastRWeb#10]
I was wondering, if there is a way to also set the HTTP status code for a WebResult (like headers). I couldn't find anything in the docs, but it would be nice, if this was possible, since a 200 is not always suitable.

**Comment by saskiaschild** [comment]
Found the answer to that:
```R
add.header("Status: 400")
```
I simply read over it. It says it in on the website: https://www.rforge.net/FastRWeb/news.html (see last bullet point under 1.1-2)

**Comment by s-u** [comment]
Yes, that is correct, I'm glad you found it even though it is somewhat buried. It is the CGI standard to set response code and status text:
https://datatracker.ietf.org/doc/html/rfc3875#section-6.3.3
