### ISSUE TITLE
match media type without parameters when decoding parameters

### ISSUE THREAD

**Issue by dckc** [s-u/FastRWeb#4]
When I post with a number of parameters in the body, info.R shows no parameters. It shows that the contente type is:

```
$ c.type      : chr "application/x-www-form-urlencoded; charset=UTF-8"
```

meanwhile, the code doesn't handle media type parameters; it just does an exact string match:

```
    if (request$c.type == 'application/x-www-form-urlencoded' && is.raw(request$body)) {
```

**Comment by dckc** [comment]
This fix seems to work:

```{R}
    if (gsub(';.*', '', request$c.type) == 'application/x-www-form-urlencoded' && is.raw(request$body)) {
```

**Comment by s-u** [comment]
Thanks, can you check if 1.1-2 fixes the issue, please?

**Comment by dckc** [comment]
That fix addresses the particular issue I ran into, but it would fail for `application/x-www-form-urlencoded-not`. Not likely a problem in practice.
