### ISSUE TITLE
Request Headers missing

### ISSUE THREAD

**Issue by satyasrikantmantha** [s-u/FastRWeb#5]
Hello Simon/,

I am using your framework to develop an analytics platform using R. I created some web apis using concepts laid down by FastRWeb, however, in order to do authentication I need to parse the request headers and verify the tokens. I noticed that in code headers are being parsed, but they are being set to expose only certain parameters like 
uri=url, method='GET', c.type='', c.length=-1, body=NULL, client.ip='0.0.0.0', query.string='', raw.cookies=''" etc.

headers are being parsed from line 67 to 78.

Would it be possible to include all the headers so that the framework can be used for authentication?

Or else I need some help in understanding how I can read custom headers from the request.

Kind regards,
Satya

**Comment by s-u** [comment]
Satya, there is no way to access arbitrary headers, since it is not part of the CGI standard. FastRWeb can only obtain whatever is provided.

That said, if you use Rserve as the http server you have much more control, because you can access everything including the headers before you pass it into the FastRWeb processing so you can pre-populate the workspace with anything you want to use including the headers. Of course, the scrupts then will use things beyond the standard API so it will only work in that setup and not in generic FastRWeb deployment.

**Comment by satyasrikantmantha** [comment]
Thanks for the quick response Simon, running Rserve standalone is an option which is on my list, and I will try that for sure. I am running my service in a docker container, and it also has static api documentation, which do require some kind of a webserver to serve static content. I see that is possible if I put my contents in /var/FastRWeb/web folder which is meant for static content. 

Thanks again for the tip and I will give it a shot.

**Comment by s-u** [comment]
FWIW my typical setup is nginx reverse proxy in front Rserve which allows a lot of flexibility (load, balancing, serving static content, redirects etc.).

**Comment by satyasrikantmantha** [comment]
Yes we have an nginx setup, behind which our microservices are present.

**Comment by satyasrikantmantha** [comment]
Simon, I was successfully able to run Rserve standalone and able to override http request parsing with my custom parse which is simply an extension of the original auth headers, now I am able to get the auth headers in all the requests. One think which is bothering me is the static web content which is sourced via  /web folder in FastRWeb. I have a swagger documentation behind it, I created an R script to serve the index page, for some reason it is not rendering in the web page.

**Comment by satyasrikantmantha** [comment]
My mistake on static content, it works. Thanks.
