### ISSUE TITLE
Status Header is always 200 OK when running RServe standalone

### ISSUE THREAD

**Issue by satyasrikantmantha** [s-u/FastRWeb#6]
Hello Simon,

I noticed that my response headers are not working properly anymore for Statuses. When I was running with CGI enabled, then I had an option to set Status. I am trying out the apis in Advanced rest client. A small screensot of script not found error is attached. 
![statuscode](https://cloud.githubusercontent.com/assets/9287965/10433851/06214864-7133-11e5-9b15-adf628013ba8.png)

Response Raw putput from Fiddler.

```
HTTP/1.1 200 OK
Content-type: text/html
Status: 404 Script not found
Content-length: 26

Script /api111.R not found
```

Kind regards,
Satya.

**Comment by s-u** [comment]
Thanks, now fixed.
