### ISSUE TITLE
Example application

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [s-u/FastRWeb#7]
Hi,
Is there any  tutorial on how to build a web app with this package?
Thanks,

**Comment by artemklevtsov** [comment]
Look at this repo: https://gitlab.com/artemklevtsov/fastrweb-ex

**Comment by s-u** [comment]
There are examples in the [web.R](https://github.com/s-u/FastRWeb/tree/master/inst/web.R) directory. Also read [INSTALL](https://github.com/s-u/FastRWeb/blob/master/INSTALL)
